import amexIcon from "../src/assets/images/creditcards/amex.png";
import discoverIcon from "../src/assets/images/creditcards/discover.png";
import mastercardIcon from "../src/assets/images/creditcards/masterCard.png";
import visaIcon from "../src/assets/images/creditcards/visa.png";

export const brandName = "Vee3D";
export const mainPageHookText = "Find premium PBR assets for your project.";
export const mainPageGoButtonText = "Our Products";

// export const fieldNames = {
//     signInEmail: "signInEmail",
//     signInPassword: "signInPassword",
//     createAccountEmail: "createAccountEmail",
//     createAccountPassword: "createAccountPassword",
//     createAccountPasswordConfirm: "createAccountPasswordConfirm",
//     createAccountFirstName: "createAccountFirstName",
//     createAccountLastName: "createAccountLastName",
//     shippingTitle: "shippingTitle",
//     shippingAddress: "shippingAddress",
//     shippingFullName: "shippingFullName",
//     shippingCity: "shippingCity",
//     shippingState: "shippingState",
//     shippingCountry: "shippingCountry",
//     shippingZip: "shippingZip",
//     paymentCardholder: "paymentCardholder",
//     paymentCardNumber: "paymentCardNumber",
//     paymentCardExpiryMonth: "paymentCardExpiryMonth",
//     paymentCardExpiryYear: "paymentCardExpiryYear",
//     paymentCardSecurityCode: "paymentCardSecurityCode",
// };

export const expressShippingPrice = 5;
export const standardShippingMinimum = 40;

export const creditCardTypes = [
    {
        start: "34",
        type: "americanExpress",
    },
    {
        start: "37",
        type: "americanExpress",
    },
    {
        start: "4",
        type: "visa",
    },
    {
        start: "5",
        type: "mastercard",
    },
    {
        start: "6",
        type: "discover",
    },
];

export const creditCardLogos = {
    americanExpress: amexIcon,
    discover: discoverIcon,
    mastercard: mastercardIcon,
    visa: visaIcon,
};

export const shippingStandardDescription = "Delivery in 4-6 business days";
export const shippingExpressDescription = "Delivery in 1-3 business days";

export const taxRate = 0.07;

export const countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "The Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Democratic Republic of the Congo",
    "Republic of the Congo",
    "Costa Rica",
    "Côte d\’Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "The Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "North Korea",
    "South Korea",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Federated States of Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "South Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];

export const PUBLIC_KEY = import.meta.env.VITE_PUBLIC_KEY;
export const SECRET_KEY = import.meta.env.VITE_SECRET_KEY;